--- 
image: "node:latest"
stages: 
  - build
  - test

cache: 
  paths: 
    - node_modules/

variables:
  NODE_ENV: 'ci-test'

services:
  - mongo:latest

install_dependencies: 
  stage: .pre
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"

build_project:
  stage: build
  script: 
    - "npm run build"

unit_tests: 
  stage: test
  script: "npm test"
