--- 
image: "node:latest"
stages: 
  - build
  - ut

cache: 
  paths: 
    - node_modules/

install_dependencies: 
  stage: build
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"

ut: 
  stage: test
  script: "npm test"
