image: node:latest

stages:
  - build
  - ut
  
cache:
  paths:
  - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

ut:
  stage: test
  script: npm test