--- 
image: "node:latest"
stages: 
  - build
  - test

cache: 
  paths: 
    - node_modules/

variables:
  MONGO_URI: 'mongodb://mongo/hrms'
  NODE_ENV: 'test'

install_dependencies: 
  stage: build
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"

unit_tests: 
  stage: test
  script: "npm test"
