--- 
cache: 
  paths: 
    - node_modules/
image: "node:latest"
install_dependencies: 
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"
  stage: build
stages: 
  - build
  - ut
ut: 
  script: "npm test"
  stage: test
